### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by HiREV-808** [ravahn/FFXIV_ACT_Plugin#114]
ERROR: [18:20:00.005] 15:, Input string was not in a correct format., StackTrace=   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at FFXIV_ACT_Plugin.Parse.LogParseData.Process(MessageType lineType, LogEntry entry, String[] data)
   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
ERROR: [18:45:52.158] 15:, Input string was not in a correct format., StackTrace=   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at FFXIV_ACT_Plugin.Parse.LogParseData.Process(MessageType lineType, LogEntry entry, String[] data)
   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
MEMORY ERROR: 254|2017-09-25T18:59:27.0770000-10:00|Bad FFXIV Packet header: 16030301BD020001B9030359C9DEAFB99D90091B4FC3C4BD
MEMORY ERROR: 254|2017-09-25T18:59:27.0770000-10:00|Correcting network buffer, Discarding [5581] of [5581] bytes from Connection 104.16.59.5:443 -> 192.168.0.25:50370: 16030301BD020001B9030359C9DEAFB99D90091B4FC3C4BDEC34ABB87B08A9B8
MEMORY ERROR: 254|2017-09-25T18:59:27.2610000-10:00|Bad FFXIV Packet header: 16030300DA040000D60000FD2000D0E86D0186940DD44B9D
MEMORY ERROR: 254|2017-09-25T18:59:27.2610000-10:00|Correcting network buffer, Discarding [274] of [274] bytes from Connection 104.16.59.5:443 -> 192.168.0.25:50370: 16030300DA040000D60000FD2000D0E86D0186940DD44B9DF84C19FA0FD91CD8
MEMORY ERROR: 254|2017-09-25T18:59:27.2610000-10:00|Bad FFXIV Packet header: 17030300400000000000000001FA9AB1A5BBD758FA5D3382
MEMORY ERROR: 254|2017-09-25T18:59:27.2610000-10:00|Correcting network buffer, Discarding [69] of [69] bytes from Connection 104.16.59.5:443 -> 192.168.0.25:50370: 17030300400000000000000001FA9AB1A5BBD758FA5D3382D3DCE8FAB54307F1
MEMORY ERROR: 254|2017-09-25T18:59:27.2610000-10:00|Bad FFXIV Packet header: 170303002100000000000000024226FF5328467583111B74
MEMORY ERROR: 254|2017-09-25T18:59:27.2610000-10:00|Correcting network buffer, Discarding [38] of [38] bytes from Connection 104.16.59.5:443 -> 192.168.0.25:50370: 170303002100000000000000024226FF5328467583111B747642261CDBBFF354
MEMORY ERROR: 254|2017-09-25T18:59:27.2610000-10:00|Bad FFXIV Packet header: 17030301F7000000000000000358A10B02D7613741F7893F
MEMORY ERROR: 254|2017-09-25T18:59:27.2610000-10:00|Correcting network buffer, Discarding [508] of [508] bytes from Connection 104.16.59.5:443 -> 192.168.0.25:50370: 17030301F7000000000000000358A10B02D7613741F7893F635DABE32F14017A
MEMORY ERROR: 254|2017-09-25T18:59:27.2610000-10:00|Bad FFXIV Packet header: 170303002100000000000000049E4D811B6F96141B748ADA
MEMORY ERROR: 254|2017-09-25T18:59:27.2610000-10:00|Correcting network buffer, Discarding [38] of [38] bytes from Connection 104.16.59.5:443 -> 192.168.0.25:50370: 170303002100000000000000049E4D811B6F96141B748ADA0A5D178098347787
MEMORY ERROR: 254|2017-09-25T19:06:07.0340000-10:00|Bad FFXIV Packet header: 170303002900000000000000052550BC12E47D46F5003391
MEMORY ERROR: 254|2017-09-25T19:06:07.0340000-10:00|Correcting network buffer, Discarding [46] of [46] bytes from Connection 104.16.59.5:443 -> 192.168.0.25:50370: 170303002900000000000000052550BC12E47D46F5003391097F27910B39B9C8
MEMORY ERROR: 254|2017-09-25T19:06:07.0340000-10:00|Bad FFXIV Packet header: 150303001A00000000000000067FCB68499924EDA6E1AE58
MEMORY ERROR: 254|2017-09-25T19:06:07.0340000-10:00|Correcting network buffer, Discarding [31] of [31] bytes from Connection 104.16.59.5:443 -> 192.168.0.25:50370: 150303001A00000000000000067FCB68499924EDA6E1AE586E3BD94D8D4312
ERROR: [19:49:15.668] 15:, Input string was not in a correct format., StackTrace=   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at FFXIV_ACT_Plugin.Parse.LogParseData.Process(MessageType lineType, LogEntry entry, String[] data)
   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
MEMORY ERROR: 254|2017-09-25T19:59:05.7760000-10:00|Bad FFXIV Packet header: 160303006802000064030359C9ECBF9D76D492F62903B518
MEMORY ERROR: 254|2017-09-25T19:59:05.7760000-10:00|Correcting network buffer, Discarding [383] of [383] bytes from Connection 104.16.58.5:443 -> 192.168.0.25:50588: 160303006802000064030359C9ECBF9D76D492F62903B518C0ADF0DC8B05910B
MEMORY ERROR: 254|2017-09-25T19:59:05.7760000-10:00|Bad FFXIV Packet header: 17030300400000000000000001EC0B6A919D29D658C44AD7
MEMORY ERROR: 254|2017-09-25T19:59:05.7760000-10:00|Correcting network buffer, Discarding [69] of [69] bytes from Connection 104.16.58.5:443 -> 192.168.0.25:50588: 17030300400000000000000001EC0B6A919D29D658C44AD7DFEBB5C5EA96D55C
MEMORY ERROR: 254|2017-09-25T19:59:05.7760000-10:00|Bad FFXIV Packet header: 17030300210000000000000002583D7A90DC999B6FBC5B31
MEMORY ERROR: 254|2017-09-25T19:59:05.7760000-10:00|Correcting network buffer, Discarding [38] of [38] bytes from Connection 104.16.58.5:443 -> 192.168.0.25:50588: 17030300210000000000000002583D7A90DC999B6FBC5B310C0A9BFB15DE8961
MEMORY ERROR: 254|2017-09-25T19:59:05.7760000-10:00|Bad FFXIV Packet header: 17030301F700000000000000030F9BA278E9459BFE56C88B
MEMORY ERROR: 254|2017-09-25T19:59:05.7760000-10:00|Correcting network buffer, Discarding [508] of [508] bytes from Connection 104.16.58.5:443 -> 192.168.0.25:50588: 17030301F700000000000000030F9BA278E9459BFE56C88B155F5F08816A52B9
MEMORY ERROR: 254|2017-09-25T19:59:05.7760000-10:00|Bad FFXIV Packet header: 170303002100000000000000049E4A48AFDD4DF4ED902346
MEMORY ERROR: 254|2017-09-25T19:59:05.7760000-10:00|Correcting network buffer, Discarding [38] of [38] bytes from Connection 104.16.58.5:443 -> 192.168.0.25:50588: 170303002100000000000000049E4A48AFDD4DF4ED9023469BCF39B492FD5FE7
MEMORY ERROR: 254|2017-09-25T20:06:01.3700000-10:00|Bad FFXIV Packet header: 17030300290000000000000005230B63B65077ABC27929BD
MEMORY ERROR: 254|2017-09-25T20:06:01.3700000-10:00|Correcting network buffer, Discarding [46] of [46] bytes from Connection 104.16.58.5:443 -> 192.168.0.25:50588: 17030300290000000000000005230B63B65077ABC27929BDECDBF30D59B3C1EE
MEMORY ERROR: 254|2017-09-25T20:06:01.3700000-10:00|Bad FFXIV Packet header: 150303001A00000000000000060A3FE613629D3A374523AE
MEMORY ERROR: 254|2017-09-25T20:06:01.3700000-10:00|Correcting network buffer, Discarding [31] of [31] bytes from Connection 104.16.58.5:443 -> 192.168.0.25:50588: 150303001A00000000000000060A3FE613629D3A374523AEFCA6AE93CB2878
MEMORY ERROR: 254|2017-09-25T20:59:25.9890000-10:00|Bad FFXIV Packet header: 16030301BD020001B9030359C9FACF6D8D5DDE21BBE769BE
MEMORY ERROR: 254|2017-09-25T20:59:25.9890000-10:00|Correcting network buffer, Discarding [5581] of [5581] bytes from Connection 104.16.59.5:443 -> 192.168.0.25:50666: 16030301BD020001B9030359C9FACF6D8D5DDE21BBE769BE19B2434EAB725CA1
MEMORY ERROR: 254|2017-09-25T20:59:25.9890000-10:00|Bad FFXIV Packet header: 16030300DA040000D60000FD2000D016AB169865CDA710D2
MEMORY ERROR: 254|2017-09-25T20:59:25.9890000-10:00|Correcting network buffer, Discarding [274] of [274] bytes from Connection 104.16.59.5:443 -> 192.168.0.25:50666: 16030300DA040000D60000FD2000D016AB169865CDA710D2086F9959BC75C669
MEMORY ERROR: 254|2017-09-25T20:59:25.9890000-10:00|Bad FFXIV Packet header: 170303004000000000000000017B5CA0CE48A6D4979ED0CC
MEMORY ERROR: 254|2017-09-25T20:59:25.9890000-10:00|Correcting network buffer, Discarding [69] of [69] bytes from Connection 104.16.59.5:443 -> 192.168.0.25:50666: 170303004000000000000000017B5CA0CE48A6D4979ED0CCA470FBE7C245778D
MEMORY ERROR: 254|2017-09-25T20:59:25.9890000-10:00|Bad FFXIV Packet header: 17030300210000000000000002FE0A619A876BDA44CFAD3B
MEMORY ERROR: 254|2017-09-25T20:59:25.9890000-10:00|Correcting network buffer, Discarding [38] of [38] bytes from Connection 104.16.59.5:443 -> 192.168.0.25:50666: 17030300210000000000000002FE0A619A876BDA44CFAD3BA6F1DF05A3B797E5
MEMORY ERROR: 254|2017-09-25T20:59:25.9890000-10:00|Bad FFXIV Packet header: 17030301F70000000000000003F7F2445A4D2AB49F25D4FD
MEMORY ERROR: 254|2017-09-25T20:59:25.9890000-10:00|Correcting network buffer, Discarding [508] of [508] bytes from Connection 104.16.59.5:443 -> 192.168.0.25:50666: 17030301F70000000000000003F7F2445A4D2AB49F25D4FDC2B43A54DE442303
MEMORY ERROR: 254|2017-09-25T20:59:25.9890000-10:00|Bad FFXIV Packet header: 1703030021000000000000000484DF976709A36ED6C0E325
MEMORY ERROR: 254|2017-09-25T20:59:25.9890000-10:00|Correcting network buffer, Discarding [38] of [38] bytes from Connection 104.16.59.5:443 -> 192.168.0.25:50666: 1703030021000000000000000484DF976709A36ED6C0E32554A24F6F02B92D6E
MEMORY ERROR: 254|2017-09-25T21:06:02.3810000-10:00|Bad FFXIV Packet header: 170303002900000000000000053B0E5DFC390EAF8EE3A675
MEMORY ERROR: 254|2017-09-25T21:06:02.3810000-10:00|Correcting network buffer, Discarding [46] of [46] bytes from Connection 104.16.59.5:443 -> 192.168.0.25:50666: 170303002900000000000000053B0E5DFC390EAF8EE3A675931D8EEE9B53C84F
MEMORY ERROR: 254|2017-09-25T21:06:02.3810000-10:00|Bad FFXIV Packet header: 150303001A0000000000000006494A58C59B687704790725
MEMORY ERROR: 254|2017-09-25T21:06:02.3810000-10:00|Correcting network buffer, Discarding [31] of [31] bytes from Connection 104.16.59.5:443 -> 192.168.0.25:50666: 150303001A0000000000000006494A58C59B6877047907259E6EC649260C2A
ERROR: [21:49:06.508] 15:, Input string was not in a correct format., StackTrace=   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at FFXIV_ACT_Plugin.Parse.LogParseData.Process(MessageType lineType, LogEntry entry, String[] data)
   at FFXIV_ACT_Plugin.Parse.LogParse.ParseData(String[] data, Boolean isImport, String& LogLineOut)
   at FFXIV_ACT_Plugin.Parse.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
MEMORY ERROR: 254|2017-09-25T21:59:21.5170000-10:00|Bad FFXIV Packet header: 16030301BD020001B9030359CA08DF1DD3067AADAA039A5A
MEMORY ERROR: 254|2017-09-25T21:59:21.5170000-10:00|Correcting network buffer, Discarding [5581] of [5581] bytes from Connection 104.16.58.5:443 -> 192.168.0.25:50755: 16030301BD020001B9030359CA08DF1DD3067AADAA039A5A7A9216A1B5315F06
MEMORY ERROR: 254|2017-09-25T21:59:21.5170000-10:00|Bad FFXIV Packet header: 16030300DA040000D60000FD2000D0D9ED6188B11A85C0DF
MEMORY ERROR: 254|2017-09-25T21:59:21.5170000-10:00|Correcting network buffer, Discarding [274] of [274] bytes from Connection 104.16.58.5:443 -> 192.168.0.25:50755: 16030300DA040000D60000FD2000D0D9ED6188B11A85C0DFBFC7BFD2A5433DE1
MEMORY ERROR: 254|2017-09-25T21:59:21.5170000-10:00|Bad FFXIV Packet header: 17030300400000000000000001726B8BD6F650EDE10E4ABF
MEMORY ERROR: 254|2017-09-25T21:59:21.5170000-10:00|Correcting network buffer, Discarding [69] of [69] bytes from Connection 104.16.58.5:443 -> 192.168.0.25:50755: 17030300400000000000000001726B8BD6F650EDE10E4ABFDB1555CDFF76ADA9
MEMORY ERROR: 254|2017-09-25T21:59:21.5170000-10:00|Bad FFXIV Packet header: 1703030021000000000000000296437F91419213BD419257
MEMORY ERROR: 254|2017-09-25T21:59:21.5170000-10:00|Correcting network buffer, Discarding [38] of [38] bytes from Connection 104.16.58.5:443 -> 192.168.0.25:50755: 1703030021000000000000000296437F91419213BD419257A433B8573C0F50EC
MEMORY ERROR: 254|2017-09-25T21:59:21.5170000-10:00|Bad FFXIV Packet header: 17030301F7000000000000000352C9A9A9E960438A4C60A1
MEMORY ERROR: 254|2017-09-25T21:59:21.5170000-10:00|Correcting network buffer, Discarding [508] of [508] bytes from Connection 104.16.58.5:443 -> 192.168.0.25:50755: 17030301F7000000000000000352C9A9A9E960438A4C60A18B74EC7EF436F8B9
MEMORY ERROR: 254|2017-09-25T21:59:21.5170000-10:00|Bad FFXIV Packet header: 17030300210000000000000004F4C3F6F8F167C93B9A006C
MEMORY ERROR: 254|2017-09-25T21:59:21.5170000-10:00|Correcting network buffer, Discarding [38] of [38] bytes from Connection 104.16.58.5:443 -> 192.168.0.25:50755: 17030300210000000000000004F4C3F6F8F167C93B9A006C64D7F392B0366E8B
MEMORY ERROR: 254|2017-09-25T22:06:05.5100000-10:00|Bad FFXIV Packet header: 170303002900000000000000059BAE44A8A1BD42D099F778
MEMORY ERROR: 254|2017-09-25T22:06:05.5100000-10:00|Correcting network buffer, Discarding [46] of [46] bytes from Connection 104.16.58.5:443 -> 192.168.0.25:50755: 170303002900000000000000059BAE44A8A1BD42D099F7781ACF784F0037FC3C
MEMORY ERROR: 254|2017-09-25T22:06:05.5100000-10:00|Bad FFXIV Packet header: 150303001A00000000000000062F2C47733F8A89406F0D0D
MEMORY ERROR: 254|2017-09-25T22:06:05.5100000-10:00|Correcting network buffer, Discarding [31] of [31] bytes from Connection 104.16.58.5:443 -> 192.168.0.25:50755: 150303001A00000000000000062F2C47733F8A89406F0D0DBD7AEE8845CDFB

Any idea what may be happening here?

**Comment by fiaba** [comment]
MEMORY ERROR: 254|2017-10-03T01:20:15.4160000+01:00|Bad FFXIV Packet header: 817E03E07B22636D64223A224449535041544348222C2264
MEMORY ERROR: 254|2017-10-03T01:20:15.4160000+01:00|Correcting network buffer, Discarding [996] of [996] bytes from Connection 127.0.0.1:6463 -> 127.0.0.1:57600: 817E03E07B22636D64223A224449535041544348222C2264617461223A7B2274
MEMORY ERROR: 254|2017-10-03T01:20:18.7483775+01:00|Bad FFXIV Packet header: 817E03E07B22636D64223A224449535041544348222C2264
MEMORY ERROR: 254|2017-10-03T01:20:18.7483775+01:00|Correcting network buffer, Discarding [996] of [996] bytes from Connection 127.0.0.1:6463 -> 127.0.0.1:57600: 817E03E07B22636D64223A224449535041544348222C2264617461223A7B2274
MEMORY ERROR: 254|2017-10-03T01:20:16.1720000+01:00|Bad FFXIV Packet header: 817E03E17B22636D64223A224449535041544348222C2264
MEMORY ERROR: 254|2017-10-03T01:20:16.1720000+01:00|Correcting network buffer, Discarding [997] of [997] bytes from Connection 127.0.0.1:6463 -> 127.0.0.1:57600: 817E03E17B22636D64223A224449535041544348222C2264617461223A7B2274
MEMORY ERROR: 254|2017-10-03T01:20:16.1720000+01:00|Bad FFXIV Packet header: 817E03E07B22636D64223A224449535041544348222C2264
MEMORY ERROR: 254|2017-10-03T01:20:16.1720000+01:00|Correcting network buffer, Discarding [996] of [996] bytes from Connection 127.0.0.1:6463 -> 127.0.0.1:57600: 817E03E07B22636D64223A224449535041544348222C2264617461223A7B2274
MEMORY ERROR: 254|2017-10-03T01:20:16.4310000+01:00|Bad FFXIV Packet header: 817E03E17B22636D64223A224449535041544348222C2264
MEMORY ERROR: 254|2017-10-03T01:20:16.4310000+01:00|Correcting network buffer, Discarding [997] of [997] bytes from Connection 127.0.0.1:6463 -> 127.0.0.1:57600: 817E03E17B22636D64223A224449535041544348222C2264617461223A7B2274



I started having the same error since like a week. There is a reason or a fix?

**Comment by ravahn** [comment]
Couple different issues here:

1) "ERROR: [18:20:00.005] 15:, Input string was not in a correct format., " - this will be fixed in the next version.

2) "Bad FFXIV Packet header: ", "Correcting network buffer" - This message appears when game data cant be decoded.  There are a couple of reasons why this could happen, however in fiaba's case this looks like a VPN? if so, go to plugins -> ffxiv settings and choose the correct local ip address from the "Local IP Address" list.   Otherwise, I'm not sure what it is.  Since it shows ffxiv using 127.0.0.1 and talking to another port on 127.0.0.1, this is not native ffxiv behavior to my knowledge.  I could be wrong, though.

3) "Correcting network buffer, Discarding [46] of [46] bytes from Connection 104.16.58.5:443 -> 192.168.0.25:50755: " - this error is usually caused by the game accessing port 443 (SSL) as a side-band communication, for example for in-game help.   You can safely ignore it, and at some point I'll add a filter to exclude port 443 completely so this goes away. Note: the plugin does not attempt to make use of this traffic since it isn't helpful for parsing.

**Comment by fiaba** [comment]
I dont have any VPN, this is why im quite concerned about this error. I googled it a bit and its actually an error with VPNs, but i dont have one.

**Comment by HiREV-808** [comment]
as of this last update for 4.1 patch that you released i dont see anymore errors. just thought id update this post. Appreciate the hard work you do :)
