### ISSUE TITLE
Can't detect memory signatures

### ISSUE THREAD

**Issue by walkingtalkingstephenhawking** [ravahn/FFXIV_ACT_Plugin#124]
this is my first time using ACT for FFXIV, and it isn't working.
i tried this on version 1.5.1.10
i'm running ACT as admin and FFXIV in DX11.

here's some info:
Error: empty signature for [Target].
ERROR: Unable to find Signature for [Target].
Error: empty signature for [ChatLog].
ERROR: Unable to find Signature for [ChatLog].
Error: empty signature for [MobArray].
ERROR: Unable to find Signature for [MobArray].
Error: empty signature for [ZoneID].
ERROR: Unable to find Signature for [ZoneID].
Error: empty signature for [ServerTime].
ERROR: Unable to find Signature for [ServerTime].
Error: empty signature for [PartyList].
ERROR: Unable to find Signature for [PartyList].
Error: empty signature for [Player].
ERROR: Unable to find Signature for [Player].
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ServerTime]
Error: Unable to read signature [MobArray]
Error: Unable to read signature [ZoneID]
Error: Unable to read signature [PartyList]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
Error: Unable to read signature [ChatLog]
and it continues with the same stuff

when i try to refresh the PID and IP address it throws this error:
![advanced combat tracker_2017-10-16_16-03-21](https://user-images.githubusercontent.com/32854941/31639302-e76a7df8-b28c-11e7-9229-dc43a7fff82f.png)

i've also tried disabling my antivirus and allowing it through the firewall, i don't know what to do next
thanks in advance

**Comment by LazyPanda3** [comment]
Same^ is there an update or way to correct this? i think it's because i haven't done the update for the enmity release because i didn't know how to add it to ACT.

**Comment by ravahn** [comment]
Hmm, that tells me it is not able to find any memory signatures in the FFXIV at all.  the most recent FFXIV updates only broke a couple signatures.  This suggests that either it is accessing the wrong FFXIV executable (the plugin only supports US/JP/DE/FR FFXIV versions, not Korean or Chinese unfortunately), or somehow an older version of the plugin is running.

Can you try the latest FFXIV plugin version - 1.6.1.1?

**Comment by EtherImperial** [comment]
Same issue with latest plugin version 1.6.1.8.  Unable to find memory signatures when attempting to test connection.  When selecting the PID from the list, after verifying that it's the correct PID the Object reference error comes up and ACT crashes. ACT error log shows the following 

*****
2018-01-30T14:51:33
Unhandled Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at FFXIV_ACT_Plugin.Memory.ScanCombatants.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
*****
This is not a new setup, this has been working since 2015.

**Comment by DefenderXY** [comment]
Playing ffxiv with ACT got all the overlays, but no information.  Plugin Parser message streams Error: unable to find Signature for [PartyList].  Help?

**Comment by glek** [comment]
@DefenderXY Your issue might have more to do with #165 than this.

**Comment by DefenderXY** [comment]
Thanks!  Good to see I am not alone with this.  :)
