### ISSUE TITLE
Inconsistent Errors

### ISSUE THREAD

**Issue by Itseotle** [ravahn/FFXIV_ACT_Plugin#193]
I recently started getting some very weird error codes in the FFXIV parsing plugin. I'm not really sure how to go about them. It was fine until recently, and I don't think anything has changed on my PC side. The errors appear that the parsing isn't keeping up? Been using the plugin for years so familiar with the usual fixes. Even still, double checked network data is good to go, and running in admin mode. Plugin version 1.7.0.13

```
`MEMORY ERROR: 254|2018-10-01T14:00:02.0000000-05:00|Monitor_MessageReceived Exception.  Message: 000001A0|1065ED5D|10055FC2|74DA0003|01490014|01110000|5BB26EB2|00000000|4646461B|0000AF02|0000AF02|34083408|E0BF03E8|000A016D|41F00000|E0000000|, System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
ERROR:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
ERROR:    at System.Collections.Generic.SortedSet`1.Enumerator.MoveNext()
ERROR:    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
ERROR:    at FFXIV_ACT_Plugin.Memory.ScanPackets.ProcessPacket(Byte[] buffer, DateTime packetDate)
ERROR: Invalid Line type    at FFXIV_ACT_Plugin.Memory.ScanPackets.Monitor_MessageReceived(String id, Int64 epoch, Byte[] message)|8895334b8e64de5685eff18151d29706
ERROR: y Druid:61:Heavy Shot:40001880:Midgardsormr:720103:14D30000:1C:618000:0:0:0:0:0:0:0:0:0:0:0:0:13690624:19407750:12000:12000:1000:1000:99.99231:99.99231:0:52413:52413:9480:2457:880:1000:105.1804:93.85815:-0.01531982:
ERROR: [14:00:59.478] 1E:Kokoki Koki' loses the effect of Devotion from Ruby Carbuncle.
ERROR: [14:00:59.478] 1A:Kokoki Koki' gains the effect of Embolden from Aythiel Parrhe for 7.38 Seconds. (2)
ERROR: [14:00:59.484] 1A:Zany Druid gains the effect of The Balance from Yann Tong for 30.00 Seconds.
ERROR: [14:00:59.484] 1A:Zany Druid gains the effect of Embolden from Aythiel Parrhe for 7.85 Seconds. (2)
ERROR: [14:00:59.000] 00:112e:⇒ Zany Druid gains the effect of The Balance.
ERROR: [14:00:59.576] 1E:Aya Starlight loses the effect of Devotion from Ruby Carbuncle.
ERROR: [14:00:59.576] 1A:Aya Starlight gains the effect of Embolden from Aythiel Parrhe for 7.66 Seconds. (2)
ERROR: [14:00:59.000] 00:112e:⇒ Aya Starlight gains the effect of The Balance.
ERROR: [14:00:59.000] 00:402b:Eos casts Embrace.
ERROR: [14:00:59.000] 00:412d:⇒ Aya Starlight recovers 5932 HP.
ERROR: [14:00:59.847] 1A:Aya Starlight gains the effect of The Balance from Yann Tong for 30.00 Seconds.
ERROR: [14:00:59.847] 1A:Aya Starlight gains the effect of Blackest Night from Elric Hellshadow for 7.00 Seconds.
ERROR: [14:00:59.847] 15:106ED47A:Aya Starlight:28:Thrill Of Battle:106ED47A:Aya Starlight:140F:570000:04:37EC0000:0:0:0:0:0:0:0:0:0:0:0:0:52742:71580:4560:4560:940:1000:99.25989:90.50122:0:52742:71580:4560:4560:940:1000:99.25989:90.50122:0:
ERROR: [14:00:59.847] 1E:Eos loses the effect of Devotion from Ruby Carbuncle.
ERROR: [14:00:59.000] 00:4430:Eos loses the effect of Devotion.
ERROR: [14:00:59.630] 0D:Aya Starlight HP at 81%.

ect. log is full of random lines that throw errors
`
```

**Comment by Itseotle** [comment]
So I figured out the reason of this. I moved my log folder to a different directory. Moving it back solved the bugs. Not sure why it would do this with admin rights but w.e
