### ISSUE TITLE
Error processing Network Data with WinPCap

### ISSUE THREAD

**Issue by rmiza** [ravahn/FFXIV_ACT_Plugin#96]
Currently trying to get Network Data working with WinPCap on Win10. I can parse for ~2-4 seconds on a training dummy, before I get the following error:

```
Unhandled Exception
System.ApplicationException: Error processing Network Data. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at FFXIV_ACT_Plugin.Memory.ScanPackets.ProcessData(IFStateObject state, Byte[] byteData, Int32 nReceived)
   at FFXIV_ACT_Plugin.Memory.ScanPackets.WinPcapWrapper_DataReceived(Object sender, DataReceivedEventArgs e)
   --- End of inner exception stack trace ---
   at FFXIV_ACT_Plugin.Memory.ScanPackets.WinPcapWrapper_DataReceived(Object sender, DataReceivedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at FFXIV_ACT_Plugin.Memory.WinPcapWrapper.OnDataReceived(DataReceivedEventArgs e)
   at FFXIV_ACT_Plugin.Memory.WinPcapWrapper.PollNetworkDevice(Object stateInfo)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by ravahn** [comment]
The network library has been re-written and moved to a new library called Machina.  I believe this issue should be resolved now, but please re-open if it is still happening.
